#!/bin/bash
# ABOUTME: Generates INDEX.md from plan files by extracting titles and summaries.
# ABOUTME: Called from archive-plan.sh at session end. Fast: grep/sed only, no jq.

set -euo pipefail

PLANS_DIR="$HOME/.claude/plans"
INDEX_FILE="$PLANS_DIR/INDEX.md"

if [[ ! -d "$PLANS_DIR" ]]; then
    exit 0
fi

# Collect plan data: date, title, filename, summary
# Skip INDEX.md itself and agent sub-files (*-agent-*)
entries=()
for plan in "$PLANS_DIR"/*.md; do
    [[ -f "$plan" ]] || continue
    filename=$(basename "$plan")

    # Skip index and agent sub-files
    [[ "$filename" == "INDEX.md" ]] && continue
    [[ "$filename" == *-agent-* ]] && continue

    # Extract modification date (macOS + Linux compatible)
    mtime=$(stat -f '%Sm' -t '%Y-%m-%d' "$plan" 2>/dev/null || stat -c '%y' "$plan" 2>/dev/null | cut -d' ' -f1)

    # Extract first # heading
    title=$(grep -m1 '^# ' "$plan" | sed 's/^# //' | head -c 100)
    if [[ -z "$title" ]]; then
        title="(untitled)"
    fi

    # Extract first non-empty line after the heading as summary
    summary=$(awk '/^# /{found=1; next} found && /^[^#[:space:]]/{print; exit} found && /^$/{next}' "$plan" | head -c 120)
    if [[ -z "$summary" ]]; then
        summary="—"
    fi
    # Escape pipe characters in summary for markdown table
    summary="${summary//|/\\|}"

    # Get mtime as epoch for sorting (macOS + Linux)
    epoch=$(stat -f '%m' "$plan" 2>/dev/null || stat -c '%Y' "$plan" 2>/dev/null)

    entries+=("${epoch}|${mtime}|${title}|${filename}|${summary}")
done

# Sort by epoch descending (newest first), then write
{
    echo "# Plan Index"
    echo ""
    echo "Auto-generated by \`index-plans.sh\`. $(date '+%Y-%m-%d %H:%M'). ${#entries[@]} plans indexed."
    echo ""
    echo "| Date | Title | File | Summary |"
    echo "|------|-------|------|---------|"

    printf '%s\n' "${entries[@]}" | sort -t'|' -k1 -rn | while IFS='|' read -r _epoch date title filename summary; do
        echo "| $date | $title | \`$filename\` | $summary |"
    done
} > "$INDEX_FILE"
